language: perl
# Use container-based infrastucture on Travis which doesn't support running
# things as root; see http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
perl:
    - "5.16"
    - "5.18"
    - "5.20"
addons:
    postgresql: "9.3"
    hosts:
        - copy-kvs.local
    apt:
        # Whitelist: https://github.com/travis-ci/apt-source-whitelist
        sources:
            # Recent version of MongoDB
            - mongodb-upstart
        # Whitelist: https://github.com/travis-ci/apt-package-whitelist
        # Keep in sync with "install_mediacloud_system_package_dependencies.sh"
        packages:
            - build-essential
            - cpanminus
            - curl
            - g++
            - gawk
            - gcc
            - make
            - mongodb-10gen
env:
    global:
        # S3 credentials for testing
        - secure: "Hh6J8E1HiIMrCUVpot3g5DpA0e2LZPCCb4jKJ4ZDuRI3UDqxL4UILfRvuPfgNckXwyH4z8OBOkrwnhgZ9fKyIwIRiW7uz1PqsVeSR9m6fxnhko2v7UiAw4aH+A4vPQPsbL9jnn1DJsyqE062ZreNwRWRsWAOqTNZnfbZnn3beJg="
        - secure: "SCI+uOWDM7APHvJFdbf02TmrurzHuhxOnLf+iFB4QSH0+j2Lmguf5K4UBYv0XQv6t60dLcS1lbtC7uhYXehyNkWa3ONdLstDM3KFk2/23YfFM1+xI3lxUXAxtMKelNd6uixAWl9Qom6XUDHC9tUS8i2nsICVD+RNsAfbLtRjxIs="
        - secure: "dL1elsbaCqXNEHZw+2Rc7nG2ANLlf9TBwaR4UY74QuHumNbEbShYKTityAXMjcQIgxBq+3ye40kj6/vipmBFD1Haot5qRpgLKL9/bR9QchCEJjfy9KYDvHttuAcgVC9a4z1Zk0jal5HMrdd7DIL7jkvs7iNh2JoDWy4R6EbS4Sk="
        # PostgreSQL credentials for testing
        - "COPY_KVS_POSTGRES_HOST=localhost"
        - "COPY_KVS_POSTGRES_USERNAME=copy_kvs_test"
        - "COPY_KVS_POSTGRES_PASSWORD=copy_kvs_test"
        - "COPY_KVS_POSTGRES_DATABASE=copy_kvs_test"
before_install:
    # Create PostgreSQL test user and database
    - psql -U postgres -c "CREATE USER copy_kvs_test WITH PASSWORD 'copy_kvs_test';"
    - psql -U postgres -c "CREATE DATABASE copy_kvs_test WITH OWNER = copy_kvs_test;"
install:
    - mongo --version
    - "mongo mydb_test --eval 'db.addUser(\"travis\", \"test\");'"
    # FIXME install older version of MongoDB Perl driver because the new one has an "empty file" bug:
    # <https://jira.mongodb.org/browse/PERL-536>
    - travis_retry cpanm --quiet --notest MongoDB@0.707.1.0
    # Install dependencies
    - travis_retry cpanm --quiet --installdeps --notest .
    # Install Devel::Cover::Report::Coveralls for Coveralls.io test coverage reporting
    - travis_retry cpanm --quiet --notest Devel::Cover::Report::Coveralls
script:
    - perl Makefile.PL
    - make
    - cover -test
    - make install
    - make clean
after_success:
    - cover -report coveralls
